/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Calendar: typeof import('./src/components/TopBar/components/special/Calendar.vue')['default']
    Dock: typeof import('./src/components/Dock/Dock.vue')['default']
    DockItem: typeof import('./src/components/Dock/DockItem.vue')['default']
    Drawer: typeof import('./src/components/common/Drawer.vue')['default']
    LaunchPad: typeof import('./src/components/LaunchPad/LaunchPad.vue')['default']
    LeftMenu: typeof import('./src/components/TopBar/LeftMenu/index.vue')['default']
    MacDropdown: typeof import('./src/components/TopBar/MacDropdown.vue')['default']
    Menu: typeof import('./src/components/TopBar/components/common/Menu.vue')['default']
    MenuItem: typeof import('./src/components/TopBar/components/common/MenuItem.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NDropdown: typeof import('naive-ui')['NDropdown']
    RightTime: typeof import('./src/components/TopBar/components/special/RightTime.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopBar: typeof import('./src/components/TopBar/TopBar.vue')['default']
    Window: typeof import('./src/components/Window/Window.vue')['default']
    WindowContent: typeof import('./src/components/Window/WindowContent.vue')['default']
    WindowHeader: typeof import('./src/components/Window/WindowHeader.vue')['default']
  }
}
